// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mar.repository;

import com.mar.repository.ScreeningRoomRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ScreeningRoomRepository_Roo_Jpa_Repository {
    
    declare @type: ScreeningRoomRepository: @Transactional(readOnly = true);
    
}
